### ISSUE TITLE
Unable to browse categories

### ISSUE THREAD

**Issue by jaykay0079** [diegofn/TuneIn-Radio-VLC#10]
Hi,

I am not able to browse sub categories within the Tunein Radio Plugins with the new version.

Regards.

**Comment by diegofn** [comment]
Hello @jaykay0079 
Can you send me a VLC log to review your problem?

Thanks for using my addon.

**Comment by sluchznak** [comment]
https://gist.github.com/sluchznak/19ab2fba5c3a65c5a478ea0ac30ddc0e - vlc log

**Comment by diegofn** [comment]
Try double click on the location tree item, for example: South America

**Comment by sluchznak** [comment]
Nothing happens

**Comment by diegofn** [comment]
It works for me, can you confirm if you download the latest version or can you send me a log when you made double click.

Remember that you must to install the tunein.lua and the radiotime.lua script too.
![screen shot 2018-05-01 at 9 44 22 pm](https://user-images.githubusercontent.com/981273/39502983-d50bb0cc-4d88-11e8-8b11-2ea1c815bf55.png)

**Comment by sluchznak** [comment]
I install plugin via readme

**Comment by sluchznak** [comment]
Yes, I'm using latest version (master)

**Comment by diegofn** [comment]
I see in the log that you dont have the radiotime.lua in /Applications/VLC.app/Contents/MacOS/share/lua/playlist/ or Users/sluchainiyznak/Library/Application Support/org.videolan.vlc/lua/playlist.

Please copy the file, restart VLC and try again

**Comment by sluchznak** [comment]
Thanks! It works!

**Comment by sluchznak** [comment]
I think something is wrong with instruction because I have no `radiotime.lua` file in paths above but i execute all `cp` commands:
```
cp TuneIn-Radio-VLC-master/tunein.lua ~/Library/Application\ Support/org.videolan.vlc/lua/sd/
cp -R TuneIn-Radio-VLC-master/playlist/* ~/Library/Application\ Support/org.videolan.vlc/lua/
```

**Comment by sluchznak** [comment]
Oh, got it. Second `cp` command is wrong

**Comment by sluchznak** [comment]
@diegofn

**Comment by diegofn** [comment]
You are right, I change the readme.md file. Thanks for your feedback :-)
