### ISSUE TITLE
Incorrect Station Information

### ISSUE THREAD

**Issue by DanielRios549** [diegofn/TuneIn-Radio-VLC#14]
I recently start using this extension and I love it, it just works, no more web apps just for listening radio. But there is a "bug" that is annoying me: when I click to play a station, it does not start immediately and opens a subfolder with 1 or even, in my case, 8 stream URLs (I think that is duplicated). These URLs do not get the correct radio information, like name and cover image.

In the image, I have only 3 stations in my favorites (102.1, 93.3 and 97.5), but I have 17 URLs to listen the stations itself, and none of them get the correct information about the station. The radio stations are those selected (you can see the cover image and the name in artist column), and the playable URLs are those with a world icon on the left (with exactly no information about the station).
![screenshot from 2018-09-08 15-03-28](https://user-images.githubusercontent.com/11152535/45257183-5fd45b00-b378-11e8-8178-1195ca434463.png)

**Comment by diegofn** [comment]
Hello,

Thanks for using this addon. However your stations are using the streamtheworld service. Those of them are using a PLS file and I can not fill with the correct information.
