### ISSUE TITLE
Random failures at start (plugin)

### ISSUE THREAD

**Issue by comxd** [diegofn/TuneIn-Radio-VLC#15]
Sometimes, _TuneIn Radio_ plugin not working:
* loader indicator turns in a loop,
* it does not display the _Trending_ item,
* only _Favorites_ item is displayed but empty

One solution is to restart VLC and go to _TuneIn Radio_ plugin until it works.

KO:
![image](https://user-images.githubusercontent.com/9022239/56131847-e4c7c880-5f88-11e9-86a6-46bbc4db5b64.png)

OK:
![image](https://user-images.githubusercontent.com/9022239/56132034-4720c900-5f89-11e9-9f1c-2d60b8edc0cb.png)

OS: (K)Ubuntu 18.10
VLC : 3.0.4

**Comment by comxd** [comment]
Related to #13

**Comment by diegofn** [comment]
Can you help me send me a VLC log when it occurs?
Best regars.

**Comment by RSABear** [comment]
I think the problem is with - require "simplexml", this file is not installed with the default VLC setup.

**Comment by comxd** [comment]
Hi,

No problems since a long time! I can close this issue, thanks for your reply.
