### ISSUE TITLE
lua probe error: lua/modules/simplexml.lua:24: attempt to call a nil value (global 'module')

### ISSUE THREAD

**Issue by stefanheijnen** [diegofn/TuneIn-Radio-VLC#18]
VLC 3.0.11.1 Vetinari (revision 3.0.11.1-0-g52483f3ca2) on Manjaro Linux 20.1 gives this error:

lua probe error: Error loading script /home/stefan/.local/share/vlc/lua/sd/tunein.lua: lua/modules/simplexml.lua:24: attempt to call a nil value (global 'module')

I installed it like this:
```
cp TuneIn-Radio-VLC-master/tunein.lua ~/.local/share/vlc/lua/sd/
cp TuneIn-Radio-VLC-master/playlist/* ~/.local/share/vlc/lua/playlist/
```

And nothing is showing up under "Internet".

**Comment by diegofn** [comment]
Please try to rollback the VLC version and test it again.

Thanks!

**Comment by stefanheijnen** [comment]
3.0.6.0 - 3.0.10: give me this error: `qt interface error: Unable to load extensions module`

I can't go further back. Downgrading is officially not supported on Manjaro.

**Comment by stefanheijnen** [comment]
For some reason Tunein does show up now, but only displays a empty folder with "My Presets".

The log shows some more info now:


```
lua error: Error loading script /home/stefan/.local/share/vlc/lua/sd/tunein.lua: /home/stefan/.local/share/vlc/lua/sd/tunein.lua:22: attempt to call global 'require' (a nil value)
http error: cannot resolve www.avrilcolombia.org: Name or service not known
access error: HTTP connection failure
main error: cannot resolve www.avrilcolombia.org port 80 : Name or service not known
http error: cannot connect to www.avrilcolombia.org:80
main error: no suitable access module for `http://www.avrilcolombia.org/VideoLAN/VLC/resources/presets.png'
access error: HTTP 403 error
http error: error: HTTP/1.1 403 Forbidden
main error: no suitable access module for `http://opml.radiotime.com/Browse.ashx?c=presets&formats=aac,html,mp3,wma,wmpro,wmvideo,wmvoice&partnerId=yvcOjvJP&username=XXX&password=XXX'
lua error: Error while running script /home/stefan/.local/share/vlc/lua/sd/tunein.lua, function main(): /home/stefan/.local/share/vlc/lua/sd/tunein.lua:150: attempt to index local 'tree' (a nil value)
```

**Comment by diegofn** [comment]
I notice that you have an older version of this addon:

Please upgrade the tunein.lua  to the following file
https://github.com/diegofn/TuneIn-Radio-VLC/blob/master/tunein.lua

**Comment by stefanheijnen** [comment]
That's strange, I downloaded the files last weekend. Anyway, I put the new file in place and everything is working again.

Thank you for your help.

**Comment by diegofn** [comment]
If you install the addon thought VLC addons manager, I will to replace the older version.

**Comment by stefanheijnen** [comment]
Yeah, now I recall. I first installed it directly from GitHub, and later through VLC itself.

**Comment by diegofn** [comment]
Sure, please uninstall from the VLC addons manager and later copy the lastest version to the lua/ directory
