### ISSUE TITLE
tunein_radio.xml example is missing

### ISSUE THREAD

**Issue by umpirsky** [diegofn/TuneIn-Radio-VLC#5]
In https://github.com/diegofn/TuneIn-Radio-VLC/blob/master/tunein-v2.lua#L68 `tunein_radio.xml` is used, but users don't know how it should look like. 

It would be nice to provide example in repository.

**Comment by diegofn** [comment]
Sure, but the tune_radio.xml location is not working on the 2.X.X version. Please don't use the version 2 of this script.
