### ISSUE TITLE
Wishlist: Create OpenWrt luci module

### ISSUE THREAD

**Issue by probonopd** [diegofn/TuneIn-Radio-VLC#7]
It would be nice if this could be turned into a module for the OpenWrt web interface luci -  https://github.com/openwrt/luci

That way one could browse stations graphically in the luci web interface.

The good thing is that luci is written in lua, too.

It is relatively easy to build a web radio out of a cheap (sub-USD-10) router and an USB sound card, see
https://github.com/probonopd/minikrebs

**Comment by diegofn** [comment]
Sorry, Can you explain us more about your requirement? how can listen radiostations in a OpenWRT hardware compatible? using Web?

**Comment by probonopd** [comment]
Please see https://github.com/probonopd/minikrebs/blob/master/doc/radio.md and https://github.com/probonopd/minikrebs/blob/master/README.md for a description on how to turn a cheap (sub-USD 20) router and a USB sound card into a radio player. It is operated via a HTML interface.

**Comment by diegofn** [comment]
Thanks for your information, I will review it and I comment you!
